name: group-pull-request-action
description: assign reviewers of pull requests by labels

inputs:
  label-prefix:
    description: prefix of label to filter
    required: true
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

runs:
  using: 'node20'
  main: 'dist/index.js'
