import * as core from '@actions/core'
import { Octokit, Repository } from './types.js'
import { PullRequestReviewGroup } from './group.js'

export const formatDashboard = (groups: PullRequestReviewGroup[]): string => {
  const lines: string[] = []
  lines.push(`\
This is automatically generated by assign-pull-request-reviewers-action.

## Pull request groups
`)
  if (groups.length === 0) {
    lines.push(`Nothing.`)
  }
  for (const group of groups) {
    lines.push(`\
### ${group.labels.join(', ')}
These pull requests are reviewed by ${group.reviewers.map((r) => `@${r}`).join(' ')}.

| Pull Request | Merged |
|--------------|--------|`)
    for (const pull of group.pulls) {
      let merged = '-'
      if (pull.merged_at) {
        merged = `:white_check_mark: ${new Date(pull.merged_at).toISOString().substring(0, 10)}`
      }
      lines.push(`| <ul><li>#${pull.number}</li></ul> | ${merged} |`)
    }
  }
  return lines.join('\n')
}

export const createOrUpdateDashboard = async (octokit: Octokit, repo: Repository, body: string) => {
  const keyLabel = 'pull-request-review-dashboard'
  const { data: issues } = await octokit.rest.issues.listForRepo({
    ...repo,
    labels: keyLabel,
    per_page: 1,
    sort: 'created',
    direction: 'asc',
  })
  const issue = issues.pop()
  if (issue) {
    core.info(`Updating the issue #${issue.number}`)
    await octokit.rest.issues.update({
      ...repo,
      issue_number: issue.number,
      title: 'Pull Request Review Dashboard',
      body,
    })
    return
  }
  core.info(`Creating an issue`)
  await octokit.rest.issues.create({
    ...repo,
    title: 'Pull Request Review Dashboard',
    labels: [keyLabel],
    body,
  })
}
