import { PullRequestReviewGroup } from './group.js'

export const formatDashboard = (groups: PullRequestReviewGroup[]): string => {
  const lines: string[] = []
  lines.push(`\
This is automatically generated by assign-pull-request-reviewers-action.
`)
  if (groups.length === 0) {
    lines.push(`Nothing.`)
  }
  for (const group of groups) {
    lines.push(`\
## ${group.labels.join(', ')}
Primary reviewer: ${group.reviewers.map((r) => `@${r}`).join(' ')}

${formatPullRequestReviewGroup(group)}
`)
  }
  return lines.join('\n')
}

export const formatComment = (group: PullRequestReviewGroup) => {
  return `\
## Related pull requests (${group.labels.join(', ')})
Primary reviewer: ${group.reviewers.map((r) => `@${r}`).join(' ')}

${formatPullRequestReviewGroup(group)}
`
}

const formatPullRequestReviewGroup = (group: PullRequestReviewGroup) => {
  const lines: string[] = []
  lines.push(`\
| Pull Request | Merged |
|--------------|--------|`)

  for (const pull of group.pulls) {
    let merged = '-'
    if (pull.merged_at) {
      merged = `:white_check_mark: ${new Date(pull.merged_at).toISOString().substring(0, 10)}`
    }
    lines.push(`| <ul><li>#${pull.number}</li></ul> | ${merged} |`)
  }
  return lines.join('\n')
}
