import { PullRequestGroup } from './group.js'

export const formatDashboard = (groups: PullRequestGroup[]): string => {
  const lines: string[] = []
  lines.push(`\
This is automatically generated by group-pull-request-action.
`)
  if (groups.length === 0) {
    lines.push(`Nothing.`)
  }
  for (const group of groups) {
    lines.push(`\
## ${group.labels.join(', ')}

${formatPullRequestGroup(group)}
`)
  }
  return lines.join('\n')
}

export const formatComment = (group: PullRequestGroup) => {
  return `\
## Related pull requests (${group.labels.join(', ')})

${formatPullRequestGroup(group)}
`
}

const formatPullRequestGroup = (group: PullRequestGroup) => {
  const lines: string[] = []
  lines.push(`\
| Pull Request | Merged |
|--------------|--------|`)

  for (const pull of group.pulls) {
    let merged = '-'
    if (pull.merged_at) {
      merged = `:white_check_mark: ${new Date(pull.merged_at).toISOString().substring(0, 10)}`
    }
    lines.push(`| <ul><li>#${pull.number}</li></ul> | ${merged} |`)
  }
  return lines.join('\n')
}
